name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**" # This will match pull requests targeting any branch

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-version:
          - "5.3"

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Environment setup
        run: |
          echo "DUNE_WORKSPACE=$PWD/dune-workspace-${{ matrix.ocaml-version }}" >> "$GITHUB_ENV"

      - name: Setup Dune
        uses: mbarbin/setup-dune@d38f7c80df59974cbe417c7f2a849219d54b4fdf # v2.0.0+patch-3
        with:
          version: "3.21.0"
          workspace: ${{ env.DUNE_WORKSPACE }}
          cache-prefix: "main-ci-${{ matrix.ocaml-version }}"
          steps: install-dune enable-pkg lazy-update-depexts install-gpatch install-depexts

      # Setting implicit_transitive_deps based on the compiler version.
      - name: Edit dune-project
        run: sed -i 's/(implicit_transitive_deps [^)]*)/(implicit_transitive_deps false)/' dune-project

      - name: Build and Run tests
        run: |
          rm -rf _build/default/
          mkdir $BISECT_DIR
          dune build @all @runtest --force --instrument-with bisect_ppx
        env:
          BISECT_DIR: ${{ runner.temp }}/_bisect_ppx_data
          BISECT_FILE: ${{ runner.temp }}/_bisect_ppx_data/data

      - name: Send coverage report to Coveralls
        run: dune exec -- bisect-ppx-report send-to Coveralls --coverage-path $BISECT_DIR
        env:
          BISECT_DIR: ${{ runner.temp }}/_bisect_ppx_data
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_NUMBER: ${{ github.event.number }}

      - name: Lint
        run: dune build @lint @fmt @unused-libs

      - name: Build Doc
        run: dune build @doc

      # Before checking for uncommitted changes we need to restore changes
      # potentially made to the dune-project file.
      - name: Restore dune-project
        run: git restore dune-project

      - name: Check for uncommitted changes
        run: git diff --exit-code
